### ISSUE TITLE
Multiple fb:admins should be specified in separated meta tags

### ISSUE THREAD

**Issue by yorkxin** [techbang/open_graph_helper#3]
Multiple `fb:admins` should be specified in separated meta tags, instead of simply concatenated by a comma `,` (U+002C), to fit Open Graph Protocol's [Array format](http://ogp.me/#array).

Although the [Comments Plug-In Document](https://developers.facebook.com/docs/reference/plugins/comments/) says:

> To add multiple moderators, separate the uids by comma without spaces.

It does actually not working, and a parser error will be warned by [Open Graph Debugger](https://developers.facebook.com/tools/debug/).

A working example should like this:

``` html
<meta property="fb:admins" content="123456">
<meta property="fb:admins" content="789012">
```

See: http://stackoverflow.com/a/12007788

**Comment by ajitsingh211** [comment]
Please suggest how to find content of my website
